Create salary model and update controllers
codelittinc/backstage-api pull request #59
Opened 2023-10-23 17:59 UTC by paulohfev

2023-10-24 18:43 UTC, kaiomagalhaes requested changes

2023-10-24 18:43 UTC, kaiomagalhaes commented on spec/factories/salaries.rb
> +    yearly_salary { 1.5 }
here it should be the yearly salary like 20000

2023-10-24 18:43 UTC, kaiomagalhaes commented on app/controllers/users_controller.rb
>    def user_params
please update the controllers tests to add this info

2023-10-24 18:43 UTC, kaiomagalhaes commented on app/controllers/users_controller.rb
>      params.require(:user).permit(:active, :contract_type, :email, :first_name, :last_name, :image_url, :seniority,
please update the user views with the salary information

2023-10-28 16:44 UTC, paulohfev commented on app/controllers/users_controller.rb
>      params.require(:user).permit(:active, :contract_type, :email, :first_name, :last_name, :image_url, :seniority,
hey @kaiomagalhaes isn't the user view already showing the info with the changes made in `_user.json.jbuilder`. I also confirmed on the `/users` endpoint, and we're returning the salaries.

2023-10-28 17:23 UTC, paulohfev commented on app/controllers/users_controller.rb
>    def user_params
hey @kaiomagalhaes in this case, do you want tests for both create and update actions?

2023-11-13 14:33 UTC, kaiomagalhaes approved these changes

2023-11-13 14:33 UTC, merged